# Generated by Django 4.1.4 on 2023-01-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_deliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
