# Generated by Django 4.1.4 on 2023-01-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_rename_is_disapproved_deliveryorder_is_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='user',
        ),
    ]
