# Generated by Django 4.1.4 on 2023-01-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_deliveryorder_city_deliveryorder_date_added_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='service',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='tax',
            field=models.IntegerField(default=10),
        ),
    ]
