# Generated by Django 4.1.4 on 2023-01-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_rename_owner_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='owner',
        ),
    ]
