# Generated by Django 4.1.4 on 2023-01-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_remove_invoice_item_deliveryorder_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='invoice',
            field=models.IntegerField(default=0),
        ),
    ]
