# Generated by Django 4.1.4 on 2023-01-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_deliveryorder_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
