# Generated by Django 4.1.4 on 2023-01-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_deliveryorder_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='invoice',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='service',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='tax',
            field=models.FloatField(default=10),
        ),
    ]
