# Generated by Django 4.1.4 on 2023-01-22 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_deliveryorder_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='city',
            field=models.CharField(default='Lake Stevens', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='date_added_order',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 1, 22, 5, 58, 24, 470995, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='home',
            field=models.CharField(default='6232', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='state',
            field=models.CharField(default='California', max_length=30),
            preserve_default=False,
        ),
    ]
